### ISSUE TITLE
obviating ZDOT_RETURN

### ISSUE THREAD

**Issue by jeffhammond** [jeffhammond/bagel#2]
Because all BLAS1 routines are bandwidth limited, there is essentially no value to using them over straightforward implementations by qualified programmers.

`ZDOT_RETURN` is a workaround for flaws in BLAS1 implementations.  I think it would be prudent to just implement dot products in BAGEL directly.

**Comment by shiozaki** [comment]
Sounds like a great idea (as long as the code is competitive with MKL; "qualified" is the key). The code should be used only when, e.g., MKL is not present.

**Comment by jeffhammond** [comment]
It's much easier than you think :-)

Intel compiler with naive C or Fortran loops should beat MKL for BLAS1 because autovectorization will be sufficient and user code is easier to inline and/or fuse.

I'll perform some experiments and share full details.

Note also that C++ loops trivially avoids any incompatibility between std::complex and Fortran complex double, should any exist (I can't remember what ISO says about this).
